[package]
name = "pecofence-render"
version.workspace = true
edition.workspace = true
license.workspace = true
autoexamples = false

[target.'cfg(windows)'.dependencies]
pecofence-core = { path = "../core" }
windows-core = { workspace = true }
windows-numerics = { workspace = true }
windows-canvas = { workspace = true }
windows-composition = { workspace = true }
windows-collections = "0.100"
windows-time = "0.100"
bezier_easing = "0.3"
pecofence-platform = { path = "../platform" }
tracing = { workspace = true }

[lints]
workspace = true
