"""Export a clean first-publication tree without development Git history."""
import hashlib
import shutil
import subprocess
import tomllib
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = (ROOT / "dist").resolve()
STAGE = (DIST / "github-source" / "PecoFence").resolve()


def main():
    top = Path(subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], cwd=ROOT, text=True
    ).strip()).resolve()
    if top != ROOT:
        raise SystemExit("Initialize this source folder as its own Git repository before exporting")
    if not STAGE.is_relative_to(DIST) or STAGE == DIST:
        raise SystemExit("Unsafe export destination")
    if (STAGE / ".git").exists():
        raise SystemExit("The export is now a Git checkout; preserve it and export to a fresh directory")
    # This exact directory is generated by this script, never a development checkout.
    if STAGE.exists():
        shutil.rmtree(STAGE)
    STAGE.mkdir(parents=True)
    output = subprocess.check_output(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
    )
    names = sorted(set(output.decode("utf-8").rstrip("\0").split("\0")))
    copied = []
    for name in names:
        source = ROOT / name
        if not source.is_file() or source.is_symlink():
            continue
        parts = Path(name).parts
        if any(part in (".git", ".cache", ".wrangler", "target", "dist", "node_modules", "__pycache__", ".capture", "out") for part in parts):
            continue
        if source.suffix.lower() in (".log", ".dmp", ".pdb", ".nupkg", ".wav", ".m4a", ".mkv", ".mp4", ".pyc"):
            continue
        if source.name.startswith(".env") and source.name != ".env.example":
            continue
        if name.startswith("extras/pecofence-promo/public/") and source.name != "README.md":
            continue
        if name.startswith("docs/history/"):
            continue
        if name.startswith("extras/pecofence-promo/review/"):
            continue
        if not source.resolve().is_relative_to(ROOT):
            raise SystemExit(f"Source leaves workspace: {name}")
        if source.stat().st_size > 50 * 1024 * 1024:
            raise SystemExit(f"Unexpectedly large source file: {name}")
        destination = STAGE / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        copied.append(name)
    version = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))["workspace"]["package"]["version"]
    archive = DIST / f"pecofence-{version}-source.zip"
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as package:
        for name in copied:
            package.write(STAGE / name, "PecoFence/" + name)
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    Path(str(archive) + ".sha256").write_text(f"{digest}  {archive.name}\n", encoding="ascii")
    print(f"Exported {len(copied)} files")
    print(f"Clean GitHub source: {STAGE}")
    print(f"Source ZIP: {archive}")


if __name__ == "__main__":
    main()
